---
name: "lint"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: ".github/workflows/lint.yml"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdown-lint
        run: markdownlint -c .github/linters/.markdown-lint.yml *.md **/*.md

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@2.0.0

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Run shfmt
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHFMT_OPTS: -l -bn -ci -i 2 -d
        with:
          sh_checker_shellcheck_disable: true

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: ".github/linters/.yamllint.yml"
